### ISSUE TITLE
Bulk file not creating

### ISSUE THREAD

**Issue by Brentbrine** [Dokucraft/Dungeons-Mod-Kit#7]
When I hit cookassests.bat it creates the .uasset and .uexp files but not the bulk file please help me.

**Comment by EvenTorset** [comment]
What is the actual issue here? Why do you need the bulk file?

UE4 only uses these files to store large bits of asset data, and they are entirely optional. The benefit of having the bulk files is a potential performance increase related to how assets are loaded, but I doubt it does much if anything in a Dungeons mod. There's a chance it doesn't generate them if the asset data is very small, but I don't know for sure if that's a thing.

If you for some reason really need the bulk file, try looking up what settings you need to change in UE4, since that's what controls this, not the mod kit. The mod kit just runs the cook process that the UE4 editor provides.

**Comment by Brentbrine** [comment]
I need the bulk file because it’s not letting my mod work without it for
some reason

**Comment by Brentbrine** [comment]
Also what setting is it in unreal engine?

**Comment by EvenTorset** [comment]
> I need the bulk file because it’s not letting my mod work without it for some reason

There are countless things that could prevent a mod from working. What makes you so sure it is the lack of a bulk file? Have you made a copy of the mod that has a bulk file and that worked?

If you did, then you should already know how to make the bulk files.

If you didn't, then I don't see how you came to the conclusion that it's specifically the bulk file missing that's the problem. It could be pretty much anything else, like some logic being wrong in a blueprint, or some settings on a texture, model, or other asset that isn't configured correctly, or it could be a file or folder name being misspelled.

> Also what setting is it in unreal engine?

Like I said, try looking it up.

**Comment by Brentbrine** [comment]
I followed Just gaming101's tutorial on modding Minecraft dungeons but when I got to the part where you're supposed to cook assets it doesn't generate the bulk file also thanks for trying to help me
